
casaba:
  sea:
    config:
      base: "https://casaba-sea-dev.dev.casaba.tech/bff/graphql"
      client-id: "test-client-id"
      client-secret: "test-client-secret"
      tenant-code: "test-tenant-code"